
- name: add nodejs repository to apt (part1)
  shell: 'curl -sL https://deb.nodesource.com/setup_10.x -o nodesource_setup.sh'
  args:
    warn: false

- name: add nodejs repository to apt (part2)
  shell: 'bash nodesource_setup.sh'

- name: install webserver dependencies 
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  with_items: 
    - nodejs
    - build-essential

- name: Clear npm cache
  shell: 'npm cache clear -f'

- name: install n globally
  npm: name=n global=yes state=latest

- name: "Install forever (program to run Node.js app)."
  npm: 
    name: forever
    global: yes
    state: present

- name: "Check list of Node.js apps running."
  command: forever list
  register: forever_list
  changed_when: false

- name: "Start Node.js app."
  command: forever start /home/ubuntu/git_files/cluster_project/app.js
  when: "forever_list.stdout.find('//home/ubuntu/git_files/cluster_project/app.js') == -1"
